version: '3'
services: 
  mongo: 
    image: "mongo:latest"
    restart: always
    networks: 
      - test
    ports: 
      - 27017:27017
    volumes: 
      - ./external/mongo:/data

  backend: 
    container_name: test-expressserver
    restart: always
    build: 
      dockerfile: Dockerfile
      context: .
    volumes: 
      - /app
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGODB_SERVER_URL=mongodb://mongo/bibliutechtest
      - SESSION_SECRET=aab2a388e9a9e55de73e9b2d5aef01c2f9a47c9
    depends_on: 
      - mongo
    networks: 
      - test
    command: npm run init-and-dev
    ports:
      - 3000:3000

networks:
  test:
    driver: bridge